# Generated by Django 2.0.7 on 2018-07-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
    ]
