# Generated by Django 2.0.7 on 2018-07-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0003_auto_20180711_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Muellif', 'verbose_name_plural': 'Muellifler'},
        ),
    ]
