# Generated by Django 2.0.7 on 2018-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0004_auto_20180711_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post-sample-image.jpg', upload_to=''),
        ),
    ]
