# Generated by Django 2.0.7 on 2018-07-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0005_auto_20180711_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menular',
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',), 'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
    ]
