# Generated by Django 2.0.7 on 2018-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0008_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
