# Generated by Django 2.0.7 on 2018-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0009_auto_20180711_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
