# Generated by Django 2.0.7 on 2018-07-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0010_footer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='SocialLink',
        ),
    ]
