# Generated by Django 2.0.7 on 2018-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0017_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='bg_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
