# Generated by Django 2.0.7 on 2018-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0018_auto_20180717_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqımızda', 'verbose_name_plural': 'Haqqımızda'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Müəllif', 'verbose_name_plural': 'Müəlliflər'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Əlaqə', 'verbose_name_plural': 'Əlaqə'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order',), 'verbose_name': 'Menyu', 'verbose_name_plural': 'Menyular'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosial şəbəkə', 'verbose_name_plural': 'Sosial şəbəkələr'},
        ),
        migrations.AlterField(
            model_name='about',
            name='bg_image',
            field=models.ImageField(default='about-bg.jpg', upload_to=''),
        ),
    ]
