# Generated by Django 2.0.7 on 2018-07-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0022_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Müəllif', 'verbose_name_plural': 'Müəlliflər'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix_app.Profile'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
