# Generated by Django 2.0.7 on 2018-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0027_auto_20180804_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='about-bg.jpg', null=True, upload_to='pictures/'),
        ),
    ]
