# Generated by Django 2.0.7 on 2018-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0029_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default='knE7cor9ntzAy1xB1h5s', max_length=20),
        ),
    ]
