# Generated by Django 2.0.7 on 2018-08-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0030_auto_20180811_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default='1QUxsvx0KXuZlAWBFizW', max_length=20),
        ),
    ]
