# Generated by Django 2.0.7 on 2018-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0032_auto_20180811_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default='xURdRmKR0LZvYTr6i26E', max_length=20),
        ),
    ]
