# Generated by Django 2.0.7 on 2018-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0034_auto_20180811_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default='RqT221tspEOSQz63vFa9', max_length=20),
        ),
    ]
