# Generated by Django 2.0.7 on 2018-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0040_auto_20180811_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Әsas Sәhifә', 'verbose_name_plural': 'Әsas Sәhifә'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order',), 'verbose_name': 'Menyu', 'verbose_name_plural': 'Menyu'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
