# Generated by Django 2.0.7 on 2018-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0041_auto_20180902_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
