# Generated by Django 2.0.7 on 2018-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0042_auto_20180902_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default='dtxP70bMQda7eB3e98aX', max_length=20),
        ),
    ]
