# Generated by Django 2.0.7 on 2019-01-04 18:29

from django.db import migrations, models
import matrix_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_app', '0043_auto_20180902_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default=matrix_app.models.random_token_generator, max_length=20),
        ),
    ]
